<?php

namespace AppBundle\Repository;

/**
 * CaracteristiquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristiquesRepository extends \Doctrine\ORM\EntityRepository
{
}
