<?php

namespace AppBundle\Repository;

/**
 * FightLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FightLogRepository extends \Doctrine\ORM\EntityRepository
{
}
