<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Perso;

/**
 * PersoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns an array of all others users Perso's
     * @param $user - the current user
     * @return Perso[]
     */
    public function findOpponent($user)
    {
        $query = $this->createQueryBuilder("persos")
            ->andWhere('persos.user <> :user')
            ->setParameter('user', $user)
            ->getQuery();

        return $query->execute();
    }

}
